[dev]
command = "npm run dev"  # Optional: for local development

[build]
command = "npm run export"
publish = "out" #"build"

[context.production]
publish = "build/"
command = "npm run export"
publish = "out"

[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview.environment]
NODE_ENV = "development"


[context.deploy-preview]
publish = "build/"

[build.environment]
NODE_ENV = "development"

[cache]
paths = ["build/**/*", ".next/cache/**/*"]  # Specify the cache paths
