[build]
command = "npm run build"
publish = "build"

[dev]
command = "npm run dev"  # Optional: for local development

[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview.environment]
NODE_ENV = "development"

[context.production]
publish = "build/"

[context.deploy-preview]
publish = "build/"

[build.environment]
NODE_ENV = "development"

[cache]
paths = ["build/**/*", ".next/cache/**/*"]  # Specify the cache paths
